# Markdownlint configuration for ASD project
# See https://github.com/DavidAnson/markdownlint for rules

# MD013 - Line length
MD013:
  # Set line length to 100 characters (consistent with Python code)
  line_length: 100
  # Number of characters for headings
  heading_line_length: 100
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include code blocks in line length checks
  code_blocks: false
  # Include tables in line length checks
  tables: false
  # Include headings in line length checks
  headings: true
  # Strict mode (fail on any violation)
  strict: false
  # Allow long lines in specific contexts
  stern: false

# MD040 - Fenced code blocks should have a language specified
MD040:
  # Require language specification for code blocks
  allowed_languages: []
  # Allow empty language specification for generic blocks
  language_only: false

# MD033 - Inline HTML
MD033:
  # Allow specific HTML elements
  allowed_elements:
    - br
    - kbd
    - sub
    - sup
